
'use client';
import React from 'react';
import { Dialog } from '@mui/material';
import AssignService from './AssignServiceCenter';

const NotificationDialog = ({ notification, onClose }) => {
  if (!notification) return null;

  const { type, data } = notification;

  return (
    <Dialog open={true} onClose={onClose}>
      <div className="p-6 w-96">
        {type === 'complaint' && (
          <AssignService data={data} />
        )}

        {type === 'warranty' && (
          <>
            <h2 className="text-lg font-bold mb-2">🛡️ Warranty Updated</h2>
            <p><strong>Product:</strong> {data?.productName}</p>
            <p><strong>New Warranty Status:</strong> {data?.newWarrantyStatus}</p>
          </>
        )}

        {type === 'sticker' && (
          <>
            <h2 className="text-lg font-bold mb-2">🏷️ Sticker Generated</h2>
            <p><strong>Sticker ID:</strong> {data?.stickerId}</p>
            <p><strong>Generated By:</strong> {data?.generatedByName}</p>
          </>
        )}

        <div className="flex justify-center mt-6">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
          >
            Dismiss
          </button>
        </div>
      </div>
    </Dialog>
  );
};

export default NotificationDialog;
